import os
os.environ.setdefault('DJANGO_SETTINGS_MODULE',
                      'fitnessWebApp.settings')

import django
django.setup()
from rango.models import Food


def populate():
    food_list = [
        {'name': 'Bagel',
         'quantity': 100,
         'calories': 310,},
         {'name': 'Biscuit digestives',
          'quantity': 100,
          'calories': 480,},
           {'name': 'Jaffa cake',
          'quantity': 100,
          'calories': 370,},
          {'name': 'Bread white(thick slice)',
          'quantity': 100,
          'calories': 240,},
          {'name': 'Bread wholemeal(thick)',
          'quantity': 100,
          'calories': 220,},
          {'name': 'Chapatis',
          'quantity': 100,
          'calories': 300,},
          {'name': 'Cornflakes',
          'quantity': 100,
          'calories': 370,},
          {'name': 'Crackerbread',
          'quantity': 100,
          'calories': 325,},
          {'name': 'Cream crackers',
          'quantity': 100,
          'calories': 440,},
          {'name': 'Crumpets',
          'quantity': 100,
          'calories': 198,},
          {'name': 'Flapjacks basic fruit mix',
          'quantity': 100,
          'calories': 500,},
          {'name': 'Macaroni (boiled)',
          'quantity': 100,
          'calories': 95,},
          {'name': 'Museli',
          'quantity': 100,
          'calories': 390,},
          {'name': 'Naan bread (normal)',
          'quantity': 100,
          'calories': 320,},
          {'name': 'Noodles',
          'quantity': 100,
          'calories': 70,},
          {'name': 'Pasta',
          'quantity': 100,
          'calories': 110,},
          {'name': 'Porridge oats (with water)',
          'quantity': 100,
          'calories': 55,},
          {'name': 'Potatoes (boiled)',
          'quantity': 100,
          'calories': 70,},
          {'name': 'Potatoes (roasted)',
          'quantity': 100,
          'calories': 140,},


          {'name': 'Rice (white boiled)',
          'quantity': 100,
          'calories': 140,},
          {'name': 'Rice (egg-fried)',
          'quantity': 100,
          'calories': 200,},
          {'name': 'Rice (brown)',
          'quantity': 100,
          'calories': 135,},
          {'name': 'Rice cakes',
          'quantity': 100,
          'calories': 373,},
          {'name': 'Ryvita Multi grain',
          'quantity': 100,
          'calories': 331,},
          {'name': 'Ryvita + seed & Oats',
          'quantity': 100,
          'calories': 362,},
          {'name': 'Spaghetti (boiled)',
          'quantity': 100,
          'calories': 101,},
          {'name': 'Anchovies tinned',
          'quantity': 100,
          'calories': 300,},
          {'name': 'Bacon average fried',
          'quantity': 100,
          'calories': 500,},
          {'name': 'Bacon average grilled',
          'quantity': 100,
          'calories': 380,},
          {'name': 'Beef (roast)',
          'quantity': 100,
          'calories': 280,},
          {'name': 'Beef burgers frozen',
          'quantity': 100,
          'calories': 280,},
          {'name': 'Chicken',
          'quantity': 100,
          'calories': 200,},
          {'name': 'Cockles',
          'quantity': 100,
          'calories': 50,},
          {'name': 'Cod fresh',
          'quantity': 100,
          'calories': 100,},
          {'name': 'Cod chip shop food',
          'quantity': 100,
          'calories': 200,},
          {'name': 'Crab fresh',
          'quantity': 100,
          'calories': 110,},
          {'name': 'Duck roast',
          'quantity': 100,
          'calories': 430,},


          {'name': 'Fish cake',
          'quantity': 100,
          'calories': 200,},
          {'name': 'Fish fingers',
          'quantity': 100,
          'calories': 220,},
          {'name': 'Gammon',
          'quantity': 100,
          'calories': 280,},
          {'name': 'Haddock fresh',
          'quantity': 100,
          'calories': 110,},
          {'name': 'Halibut fresh',
          'quantity': 100,
          'calories': 125,},
          {'name': 'Ham',
          'quantity': 100,
          'calories': 240,},
          {'name': 'Herring fresh grilled',
          'quantity': 100,
          'calories': 200,},
          {'name': 'Kidney',
          'quantity': 100,
          'calories': 160,},
          {'name': 'Kipper',
          'quantity': 100,
          'calories': 120,},
          {'name': 'Liver',
          'quantity': 100,
          'calories': 150,},
          {'name': 'Liver plate',
          'quantity': 100,
          'calories': 300,},
          {'name': 'Lamb (roast)',
          'quantity': 100,
          'calories': 300,},
          {'name': 'Lobster boiled',
          'quantity': 100,
          'calories': 100,},
          {'name': 'Luncheon meat',
          'quantity': 100,
          'calories': 400,},
          {'name': 'Mackreal',
          'quantity': 100,
          'calories': 300,},
          {'name': 'Mussels',
          'quantity': 100,
          'calories': 90,},
          {'name': 'Pheasant roast',
          'quantity': 100,
          'calories': 200,},
          {'name': 'Pilchards (tinned)',
          'quantity': 100,
          'calories': 140,},
          {'name': 'Prawns',
          'quantity': 100,
          'calories': 100,},
          {'name': 'Pork',
          'quantity': 100,
          'calories': 290,},
          {'name': 'Pork pie',
          'quantity': 100,
          'calories': 450,},
          {'name': 'Rabbit',
          'quantity': 100,
          'calories': 180,},
          {'name': 'Salmon fresh',
          'quantity': 100,
          'calories': 180,},
          {'name': 'Sardines tinned in oil',
          'quantity': 100,
          'calories': 220,},
          {'name': 'Sardines in tomato sauce',
          'quantity': 100,
          'calories': 180,},
          {'name': 'Sausage pork fried',
          'quantity': 100,
          'calories': 320,},
          {'name': 'Sausage pork grilled',
          'quantity': 100,
          'calories': 280,},
          {'name': 'Sausage roll',
          'quantity': 100,
          'calories': 480,},
          {'name': 'Scampi fried in oil',
          'quantity': 100,
          'calories': 340,},
          {'name': 'Steak & kidney pie',
          'quantity': 100,
          'calories': 350,},


          {'name': 'Taramasalata',
          'quantity': 100,
          'calories': 490,},
          {'name': 'Trout fresh',
          'quantity': 100,
          'calories': 120,},
          {'name': 'Tuna tinned water',
          'quantity': 100,
          'calories': 100,},
          {'name': 'Tuna tinned oil',
          'quantity': 100,
          'calories': 180,},
          {'name': 'Turkey',
          'quantity': 100,
          'calories': 160,},
          {'name': 'Veal',
          'quantity': 100,
          'calories': 240,},

          {'name': 'Apple',
          'quantity': 100,
          'calories': 44,},
          {'name': 'Banana',
          'quantity': 100,
          'calories': 65,},
          {'name': 'Beans baked beans',
          'quantity': 100,
          'calories': 80,},
          {'name': 'Beans dried (boiled)',
          'quantity': 100,
          'calories': 130,},
          {'name': 'Blackberries',
          'quantity': 100,
          'calories': 25,},
          {'name': 'Blackcurrant',
          'quantity': 100,
          'calories': 30,},
          {'name': 'Broccoli',
          'quantity': 100,
          'calories': 32,},
          {'name': 'Cabbage (boiled)',
          'quantity': 100,
          'calories': 20,},
          {'name': 'Carrot(boiled)',
          'quantity': 100,
          'calories': 25,},
          {'name': 'Celery (boiled)',
          'quantity': 100,
          'calories': 10,},
          {'name': 'Cherry',
          'quantity': 100,
          'calories': 50,},
          {'name': 'Courgette',
          'quantity': 100,
          'calories': 20,},
          {'name': 'Cucumber',
          'quantity': 100,
          'calories': 10,},
          {'name': 'Dates',
          'quantity': 100,
          'calories': 235,},
          {'name': 'Grapes',
          'quantity': 100,
          'calories': 62,},
          {'name': 'Grapefruit',
          'quantity': 100,
          'calories': 32,},
          {'name': 'Kiwi',
          'quantity': 100,
          'calories': 50,},
          {'name': 'Leek (boiled)',
          'quantity': 100,
          'calories': 20,},


          {'name': 'Lentils (boiled)',
          'quantity': 100,
          'calories': 100,},
          {'name': 'Lettuce',
          'quantity': 100,
          'calories': 15,},
          {'name': 'Melon',
          'quantity': 100,
          'calories': 28,},
          {'name': 'Mushrooms raw one average',
          'quantity': 100,
          'calories': 15,},
          {'name': 'Mushrooms (boiled)',
          'quantity': 100,
          'calories': 12,},
          {'name': 'Mushrooms (fried)',
          'quantity': 100,
          'calories': 145,},
          {'name': 'Olives',
          'quantity': 100,
          'calories': 80,},
          {'name': 'Onion (boiled)',
          'quantity': 100,
          'calories': 18,},
          {'name': 'One red Onion',
          'quantity': 100,
          'calories': 33,},
          {'name': 'Onions spring',
          'quantity': 100,
          'calories': 25,},
          {'name': 'Onion (fried)',
          'quantity': 100,
          'calories': 155,},
          {'name': 'Orange',
          'quantity': 100,
          'calories': 30,},
          {'name': 'Peas',
          'quantity': 100,
          'calories': 148,},
          {'name': 'Peas dried & boiled',
          'quantity': 100,
          'calories': 120,},
          {'name': 'Peach',
          'quantity': 100,
          'calories': 30,},
          {'name': 'Pear',
          'quantity': 100,
          'calories': 38,},
          {'name': 'Pepper yellow',
          'quantity': 100,
          'calories': 16,},
          {'name': 'Pineapple',
          'quantity': 100,
          'calories': 40,},
          {'name': 'Plum',
          'quantity': 100,
          'calories': 39,},
          {'name': 'Spinach',
          'quantity': 100,
          'calories': 8,},
          {'name': 'Strawberries (1 average)',
          'quantity': 100,
          'calories': 30,},
          {'name': 'Sweetcorn',
          'quantity': 100,
          'calories': 130,},
          {'name': 'Sweetcorn on the cob',
          'quantity': 100,
          'calories': 70,},
          {'name': 'Tomato',
          'quantity': 100,
          'calories': 20,},
          {'name': 'Tomato cherry',
          'quantity': 100,
          'calories': 17,},
          {'name': 'Tomato puree',
          'quantity': 100,
          'calories': 70,},
          {'name': 'Watercress',
          'quantity': 100,
          'calories': 20,},


          {'name': 'Cheese average',
          'quantity': 100,
          'calories': 440,},
          {'name': 'Cheddar types average reduced fat',
          'quantity': 100,
          'calories': 260,},
          {'name': 'Cheese spreads average',
          'quantity': 100,
          'calories': 270,},
          {'name': 'Cottage cheese low fat',
          'quantity': 100,
          'calories': 80,},
          {'name': 'Cottage cheese',
          'quantity': 100,
          'calories': 98,},
          {'name': 'Cream cheese',
          'quantity': 100,
          'calories': 428,},
          {'name': 'Cream fresh half',
          'quantity': 100,
          'calories': 160,},
          {'name': 'Cream fresh single',
          'quantity': 100,
          'calories': 200,},
          {'name': 'Cream fresh double',
          'quantity': 100,
          'calories': 430,},
          {'name': 'Cream fresh clotted',
          'quantity': 100,
          'calories': 600,},
          {'name': 'Custard',
          'quantity': 100,
          'calories': 100,},
          {'name': 'Eggs (1 average size)',
          'quantity': 100,
          'calories': 150,},
          {'name': 'Eggs fried',
          'quantity': 100,
          'calories': 180,},
          {'name': 'Fromage frais',
          'quantity': 100,
          'calories': 125,},
          {'name': 'Ice cream',
          'quantity': 100,
          'calories': 180,},
          {'name': 'Milk whole',
          'quantity': 100,
          'calories': 70,},
          {'name': 'Milk semi-skimmed',
          'quantity': 100,
          'calories': 50,},
          {'name': 'Milk skimmed',
          'quantity': 100,
          'calories': 38,},
          {'name': 'Milk soya',
          'quantity': 100,
          'calories': 36,},
          {'name': 'Omlette with cheese',
          'quantity': 100,
          'calories': 266,},
          {'name': 'Trifle with cream',
          'quantity': 100,
          'calories': 190,},
          {'name': 'Yogurt natural',
          'quantity': 100,
          'calories': 60,},
          {'name': 'Yogurt reduced fat',
          'quantity': 100,
          'calories': 45,},


          {'name': 'Bombay mix',
          'quantity': 100,
          'calories': 500,},
          {'name': 'Butter',
          'quantity': 100,
          'calories': 750,},
          {'name': 'Chewing gum',
          'quantity': 100,
          'calories': 0,},
          {'name': 'Chocolate',
          'quantity': 100,
          'calories': 500,},
          {'name': 'Cod liver oil',
          'quantity': 100,
          'calories': 900,},
          {'name': 'Corn snack',
          'quantity': 100,
          'calories': 500,},
          {'name': 'Crisps (chips US) average',
          'quantity': 100,
          'calories': 500,},
          {'name': 'Honey',
          'quantity': 100,
          'calories': 280,},
          {'name': 'Jam',
          'quantity': 100,
          'calories': 250,},
          {'name': 'Lard',
          'quantity': 100,
          'calories': 890,},
          {'name': 'Low fat spread',
          'quantity': 100,
          'calories': 400,},
          {'name': 'Margarine',
          'quantity': 100,
          'calories': 750,},
          {'name': 'Mars bars',
          'quantity': 100,
          'calories': 480,},
          {'name': 'Mint sweets',
          'quantity': 100,
          'calories': 0,},
          {'name': 'Oils -corn, sunflower, olive',
          'quantity': 100,
          'calories': 900,},
          {'name': 'Popcorn average',
          'quantity': 100,
          'calories': 460,},
          {'name': 'Sugar white table sugar',
          'quantity': 100,
          'calories': 400,},
          {'name': 'Sweets (boiled)',
          'quantity': 100,
          'calories': 300,},
          {'name': 'Syrup',
          'quantity': 100,
          'calories': 300,},
          {'name': 'Toffee',
          'quantity': 100,
          'calories': 400,}]

    for food in food_list:
        add_food(food['name'], food['quantity'], food['calories'])

def add_food(name, quantity, calories):
    f = Food.objects.get_or_create(name=name, quantity=quantity, calorie=calories)[0]
    f.name = name
    f.quantity = quantity
    f.calorie = calories
    f.save()
    return f

if __name__ == '__main__':
    print('Starting Rango population script...')
    populate()
